# Generated by Django 5.0.4 on 2024-07-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_emploi_occoupee', models.DateField(verbose_name='date occupée')),
                ('date_emploi_fixee', models.DateTimeField(verbose_name='date non occupée')),
                ('emploi_vide', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
